name = "GRUtils"
uuid = "0337cf30-a0fd-11e9-31db-a79914c9d7ac"
authors = ["Helios De Rosario"]
version = "0.8.4"

[deps]
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
GR = "0.63, 0.64, 0.66, 0.67, 0.68, 0.69, 0.70, 0.71, 0.72, 0.73"
julia = "1.10"

[extras]
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["GR", "Test", "Random", "Printf"]
